server:
  port: 8083

spring:
  application:
    name: cm-chat
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yc_project?serverTimezone=UTC
    username: root
    password: root